In [1]:
import numpy as np
import scipy.stats as st

<b>Завдання 1</b>. Перевірка гіпотези однорідності.

<p><b>A</b>. Критерій пустих блоків. Генеруємо дві незалежні вибірки:</p>
<p>X=(x_1,...,x_n) ~ F_{ksi}(u)=1-e^{-u},u>=0;</p>
<p>Y=(y_1,...,y_m) ~ F_{eta}=1-e^{1.1*u},u>=0.</p>
<p>За допомогою критерію пустих блоків перевірити гіпотезу однорідності при наступних значеннях параметрів:</p>
<p>а)n=500,m=1000 ; b)n=5000,m=10000 ; с)n=50000,m=100000 .</p>

In [40]:
def blank_boxes(x,y):
    n=len(x)
    m=len(y)
    p=m/n
    z = st.norm.ppf(1-0.05)
    criteria=n/(1+p)+np.sqrt(n)*z*p/((1+p)**(3/2))
    x_sorted=np.sort(x)
    a=0
    if len(y[y<x_sorted[0]]) == 0:
        a+=1
    for i in range(len(x_sorted)-1):
        if len(y[(x_sorted[i]<y) & (y<x_sorted[i+1])]) == 0:
            a+=1
    if len(y[y>x_sorted[n-1]]) == 0:
        a+=1
        
    print(f'приблизні значення x_sort: {x_sorted[0:3]}')
    print(f'n = {n}')
    print(f'm = {m}')
    print(f'p = {p}')
    print(f'z = {z}')
    print(f'criteria = {criteria}')
    print(f'Кількість блоків alpha = {a}')
    if a<criteria:
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
    
def taskA():
    l_x=1
    l_y=1.1
    x=np.random.exponential(scale=1/l_x,size=500)
    y=np.random.exponential(scale=1/l_y,size=1000)
    blank_boxes(x,y)
    x=np.random.exponential(scale=1/l_x,size=5000)
    y=np.random.exponential(scale=1/l_y,size=10000)
    blank_boxes(x,y)
    x=np.random.exponential(scale=1/l_x,size=50000)
    y=np.random.exponential(scale=1/l_y,size=100000)
    blank_boxes(x,y)
taskA()

приблизні значення x_sort: [0.00637283 0.0066006  0.00678196]
n = 500
m = 1000
p = 2.0
z = 1.6448536269514722
criteria = 180.8233126758487
Кількість блоків alpha = 160
Статистичні дані не суперечать гіпотезі H_0

приблизні значення x_sort: [9.18775892e-05 1.55697744e-04 4.40199753e-04]
n = 5000
m = 10000
p = 2.0
z = 1.6448536269514722
criteria = 1711.433912084415
Кількість блоків alpha = 1670
Статистичні дані не суперечать гіпотезі H_0

приблизні значення x_sort: [5.17835461e-05 5.45803978e-05 5.94105629e-05]
n = 50000
m = 100000
p = 2.0
z = 1.6448536269514722
criteria = 16808.23312675849
Кількість блоків alpha = 16659
Статистичні дані не суперечать гіпотезі H_0



<p><b>В</b>. Критерій X^2. Генеруємо три серії незалежних спостережень:</p>
<p>X=(x_1,...,x_n) ~ F_{ksi}(u)=1-e^{-u},u>=0;</p>
<p>Y=(y_1,...,y_m) ~ F_{eta}=1-e^{-u},u>=0.</p>
<p>Z=(z_1,...,z_k) ~ F_{dzeta}=1-e^{-1.1*u},u>=0</p>
<p>За допомогою критерію X^2 перевірити гіпотезу однорідності при наступних значеннях параметрів:</p>
<p>а)n=200,m=600,k=400;</p>
<p>b)n=2000,m=6000,k=4000;</p>
<p>с)n=20000,m=60000,k=40000 .</p>
<b>Зауваження.</b> Кількість  проміжків і самі проміжки  обирати самостійно.

In [145]:
def select_max(selection):
    maximum=selection[0][0]
    for array in selection:
        temp_max = np.max(array)
        if temp_max > maximum:
            maximum=temp_max
    return maximum

def form_v(selection,U):
    r=len(U)
    k=len(selection)
    v=np.zeros((k,r))
    i=0
    for array in selection:
        for j in range(r-1):
            v[i][j]=len(array[(U[j]<array)&(array<=U[j+1])])
        i+=1
    return v  
    

def chi2(selection,g,r):
    print(f'\nr = {r}')
    k=len(selection)
    maximum = select_max(selection)
    U = np.linspace(0, maximum, r) 
    v=form_v(selection,U)
    v_j=[0]*r
    for j in range(r):
        for i in range(k):
            v_j[j]+=v[i][j]
    
    n_i=[0]*len(selection)
    for i in range(k):
        n_i[i]=len(selection[i])
    n=np.sum(n_i)
    
    sum=0.0
    for i in range(k):
        for j in range(r):
            if v_j[j] != 0.0:
                sum+=(v[i][j]-(n_i[i]*v_j[j])/n)**2
                sum/=(n_i[i]*v_j[j])
    delta=n*(sum)
    z = st.chi2.ppf(1-g,(r-1)*(k-1))
    print(f'Максимальне значення в вибірці: {maximum}')
    print(f'U = {U[0:4]}')
    print(f'v = \n{v}')
    print(f'v_j = {v_j}')
    print(f'n_i = {n_i}')
    print(f'n = {n}')
    print(f'delta = {delta}')
    print(f'z = {z}')
    if delta < z:
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
    


def taskB():
    l_x=1
    l_y=1
    l_z=1.1
    gamma=0.05
    r=11
    x=np.random.exponential(scale=1/l_x,size=200)
    y=np.random.exponential(scale=1/l_y,size=600)
    z=np.random.exponential(scale=1/l_z,size=400)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
    
    x=np.random.exponential(scale=1/l_x,size=2000)
    y=np.random.exponential(scale=1/l_y,size=6000)
    z=np.random.exponential(scale=1/l_z,size=4000)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
    
    x=np.random.exponential(scale=1/l_x,size=20000)
    y=np.random.exponential(scale=1/l_y,size=60000)
    z=np.random.exponential(scale=1/l_z,size=40000)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
        
taskB()



r = 11
Максимальне значення в вибірці: 6.992565991867883
U = [0.        0.6992566 1.3985132 2.0977698]
v = 
[[ 96.  49.  28.  15.   6.   3.   2.   1.   0.   0.   0.]
 [310. 138.  77.  32.  13.  18.   5.   3.   2.   2.   0.]
 [216.  92.  54.  25.  10.   3.   0.   0.   0.   0.   0.]]
v_j = [622.0, 279.0, 159.0, 72.0, 29.0, 24.0, 7.0, 4.0, 2.0, 2.0, 0.0]
n_i = [200, 600, 400]
n = 1200
delta = 0.667502085613069
z = 31.410432844230918
Статистичні дані не суперечать гіпотезі H_0


r = 11
Максимальне значення в вибірці: 9.461216230338726
U = [0.         0.94612162 1.89224325 2.83836487]
v = 
[[1.222e+03 4.590e+02 1.980e+02 7.900e+01 2.900e+01 9.000e+00 3.000e+00
  1.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [3.670e+03 1.394e+03 5.510e+02 2.400e+02 7.900e+01 4.300e+01 1.000e+01
  1.000e+01 2.000e+00 1.000e+00 0.000e+00]
 [2.579e+03 9.060e+02 3.330e+02 1.200e+02 4.000e+01 1.300e+01 3.000e+00
  3.000e+00 1.000e+00 2.000e+00 0.000e+00]]
v_j = [7471.0, 2759.0, 1082.0, 439.0, 148.0, 65.0, 16.0, 14.0