In [1]:
import numpy as np
import scipy.stats as st

<b>Завдання 1</b>. Перевірка гіпотези однорідності.

<p><b>A</b>. Критерій пустих блоків. Генеруємо дві незалежні вибірки:</p>
<p>X=(x_1,...,x_n) ~ F_{ksi}(u)=1-e^{-u},u>=0;</p>
<p>Y=(y_1,...,y_m) ~ F_{eta}=1-e^{1.1*u},u>=0.</p>
<p>За допомогою критерію пустих блоків перевірити гіпотезу однорідності при наступних значеннях параметрів:</p>
<p>а)n=500,m=1000 ; b)n=5000,m=10000 ; с)n=50000,m=100000 .</p>

In [2]:
def blank_boxes(x,y):
    n=len(x)
    m=len(y)
    p=m/n
    z = st.norm.ppf(1-0.05)
    criteria=n/(1+p)+np.sqrt(n)*z*p/((1+p)**(3/2))
    x_sorted=np.sort(x)
    a=0
    if len(y[y<x_sorted[0]]) == 0:
        a+=1
    for i in range(len(x_sorted)-1):
        if len(y[(x_sorted[i]<y) & (y<x_sorted[i+1])]) == 0:
            a+=1
    if len(y[y>x_sorted[n-1]]) == 0:
        a+=1
        
    print(f'приблизні значення x_sort: {x_sorted[0:3]}')
    print(f'n = {n}')
    print(f'm = {m}')
    print(f'p = {p}')
    print(f'z = {z}')
    print(f'criteria = {criteria}')
    print(f'Кількість блоків alpha = {a}')
    if a<criteria:
        print(f'a < criteria')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'a >= criteria')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
    
def taskA():
    l_x=1
    l_y=1.1
    x=np.random.exponential(scale=1/l_x,size=500)
    y=np.random.exponential(scale=1/l_y,size=1000)
    blank_boxes(x,y)
    x=np.random.exponential(scale=1/l_x,size=5000)
    y=np.random.exponential(scale=1/l_y,size=10000)
    blank_boxes(x,y)
    x=np.random.exponential(scale=1/l_x,size=50000)
    y=np.random.exponential(scale=1/l_y,size=100000)
    blank_boxes(x,y)
taskA()

приблизні значення x_sort: [0.00151402 0.00176305 0.00224197]
n = 500
m = 1000
p = 2.0
z = 1.6448536269514722
criteria = 180.8233126758487
Кількість блоків alpha = 168
a < criteria
Статистичні дані не суперечать гіпотезі H_0

приблизні значення x_sort: [7.94018329e-05 3.47325003e-04 7.63284122e-04]
n = 5000
m = 10000
p = 2.0
z = 1.6448536269514722
criteria = 1711.433912084415
Кількість блоків alpha = 1649
a < criteria
Статистичні дані не суперечать гіпотезі H_0

приблизні значення x_sort: [3.49149639e-05 3.91560886e-05 5.85232189e-05]
n = 50000
m = 100000
p = 2.0
z = 1.6448536269514722
criteria = 16808.23312675849
Кількість блоків alpha = 16764
a < criteria
Статистичні дані не суперечать гіпотезі H_0



<p><b>В</b>. Критерій X^2. Генеруємо три серії незалежних спостережень:</p>
<p>X=(x_1,...,x_n) ~ F_{ksi}(u)=1-e^{-u},u>=0;</p>
<p>Y=(y_1,...,y_m) ~ F_{eta}=1-e^{-u},u>=0.</p>
<p>Z=(z_1,...,z_k) ~ F_{dzeta}=1-e^{-1.1*u},u>=0</p>
<p>За допомогою критерію X^2 перевірити гіпотезу однорідності при наступних значеннях параметрів:</p>
<p>а)n=200,m=600,k=400;</p>
<p>b)n=2000,m=6000,k=4000;</p>
<p>с)n=20000,m=60000,k=40000 .</p>
<b>Зауваження.</b> Кількість  проміжків і самі проміжки  обирати самостійно.

In [3]:
def select_max(selection):
    maximum=selection[0][0]
    for array in selection:
        temp_max = np.max(array)
        if temp_max > maximum:
            maximum=temp_max
    return maximum

def form_v(selection,U):
    r=len(U)
    k=len(selection)
    v=np.zeros((k,r))
    i=0
    for array in selection:
        for j in range(r-1):
            v[i][j]=len(array[(U[j]<array)&(array<=U[j+1])])
        i+=1
    return v  
    

def chi2(selection,g,r):
    print(f'\nr = {r}')
    k=len(selection)
    maximum = select_max(selection)
    U = np.linspace(0, maximum, r) 
    v=form_v(selection,U)
    v_j=[0]*r
    for j in range(r):
        for i in range(k):
            v_j[j]+=v[i][j]
    
    n_i=[0]*len(selection)
    for i in range(k):
        n_i[i]=len(selection[i])
    n=np.sum(n_i)
    
    sum=0.0
    for i in range(k):
        for j in range(r):
            if v_j[j] != 0.0:
                sum+=(v[i][j]-(n_i[i]*v_j[j])/n)**2
                sum/=(n_i[i]*v_j[j])
    delta=n*(sum)
    z = st.chi2.ppf(1-g,(r-1)*(k-1))
    print(f'Максимальне значення в вибірці: {maximum}')
    print(f'U = {U[0:4]}')
    print(f'v = \n{v[0:4,0:4]} ...')
    print(f'v_j = {v_j[0:4]}')
    print(f'n_i = {n_i[0:4]}')
    print(f'n = {n}')
    print(f'delta = {delta}')
    print(f'z = {z}')
    if delta < z:
        print(f'delta < z')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'delta >= z')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')


def taskB():
    l_x=1
    l_y=1
    l_z=1.1
    gamma=0.05
    r=100
    x=np.random.exponential(scale=1/l_x,size=200)
    y=np.random.exponential(scale=1/l_y,size=600)
    z=np.random.exponential(scale=1/l_z,size=400)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
    
    r=1000
    x=np.random.exponential(scale=1/l_x,size=2000)
    y=np.random.exponential(scale=1/l_y,size=6000)
    z=np.random.exponential(scale=1/l_z,size=4000)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
    
    r=10000
    x=np.random.exponential(scale=1/l_x,size=20000)
    y=np.random.exponential(scale=1/l_y,size=60000)
    z=np.random.exponential(scale=1/l_z,size=40000)
    selection=np.array([x,y,z])
    chi2(selection,gamma,r)
        
taskB()



r = 100
Максимальне значення в вибірці: 6.758235526000619
U = [0.         0.06826501 0.13653001 0.20479502]
v = 
[[ 9. 18. 10.  6.]
 [43. 44. 27. 25.]
 [29. 29. 22. 24.]] ...
v_j = [81.0, 91.0, 59.0, 55.0]
n_i = [200, 600, 400]
n = 1200
delta = 0.3366687552213868
z = 231.82916671052752
delta < z
Статистичні дані не суперечать гіпотезі H_0


r = 1000
Максимальне значення в вибірці: 11.219995478994136
U = [0.         0.01123123 0.02246245 0.03369368]
v = 
[[32. 21. 18. 23.]
 [66. 74. 72. 50.]
 [41. 42. 41. 39.]] ...
v_j = [139.0, 137.0, 131.0, 112.0]
n_i = [2000, 6000, 4000]
n = 12000
delta = 0.33341675000520965
z = 2103.102202045826
delta < z
Статистичні дані не суперечать гіпотезі H_0


r = 10000
Максимальне значення в вибірці: 12.965954722388247
U = [0.         0.00129673 0.00259345 0.00389018]
v = 
[[20. 28. 22. 22.]
 [79. 60. 75. 79.]
 [59. 59. 79. 57.]] ...
v_j = [158.0, 147.0, 176.0, 158.0]
n_i = [20000, 60000, 40000]
n = 120000
delta = 0.3333416675000052
z = 20328.08737478791
de

<b>Завдання 2</b>. Перевірка гіпотези незалежності.
<p>Генеруємо вибірку (X,Y) за наступним правилом:
{x_i} - це реалізації рівномірно розподіленої на [0,1]
випадкової величини ksi, а {y_i} - це реалізації випадкової величини ksi+eta, де eta має рівномірний розподіл на проміжку [-1,1], тобто (x_i,y_i)=(ksi_i,ksi_i+eta_i)</p>

<b>А. Критерій X^2.</b>
<p>Перевірити гіпотезу незалежності за допомогою критерія Х^2 при наступних значеннях параметра n:</p>
<p> а) n=500 ; b) n=5000 ; с) n=50000</p>
<p>Зауваження. Значення r та k, а також самі проміжки U_i,i=1,...r та V_j,j=1,...,k обирати самостійно.</p>

In [4]:
def chi2_independence(X,Y,r,k,g):
    print(f'r = {r}')
    print(f'k = {k}')
    n=len(X)
    X_max=np.max(X)
    Y_max=np.max(Y)
    X_min=np.min(X)
    Y_min=np.min(Y)
    U_X=np.linspace(0,1,r)
    U_Y=np.linspace(-1,2,k)
    v=np.zeros((r-1,k-1))
    for i in range(r-1):
        for j in range(k-1):
            X_temp = X[(U_X[i] < X) & (X <= U_X[i+1])]
            Y_temp = Y[(U_Y[j] < Y) & (Y <= U_Y[j+1])]
            v[i][j] = len(X_temp) + len(Y_temp)
    v_i=np.zeros(r-1)#r=5
    v_j=np.zeros(k-1)#k=10
    for i in range(r-1):
        for j in range(k-1):
            v_i[i]+=v[i][j]
    for j in range(k-1):
        for i in range(r-1):
            v_j[j]+=v[i][j]
    sum=0.0
    for i in range(r-1):
        for j in range(k-1):
            sum+=(v[i][j]-(v_i[i]*v_j[j]/n))**2
            sum/=(v_i[i]*v_j[j])
    delta=n*sum
    z = st.chi2.ppf(1-g,(r-1)*(k-1))
    print(f'U_X: {U_X[0:4]}')
    print(f'U_Y: {U_Y[0:4]}')
    print(f'v:\n ={v[0:4,0:4]}...')
    print(f'v_i: {v_i[0:4]}')
    print(f'v_j: {v_j[0:4]}')
    print(f'delta = {delta}')
    print(f'z = {z}')
    if delta < z:
        print(f'delta < z')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'delta >= z')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
    

def taskA():
    g=0.05
    
    n=500
    r=10
    k=15
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    chi2_independence(X,Y,r,k,g)
    
    n=5000
    r=50
    k=55
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    chi2_independence(X,Y,r,k,g)
    
    n=50000
    r=100
    k=105
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    chi2_independence(X,Y,r,k,g)
    
taskA()

r = 10
k = 15
U_X: [0.         0.11111111 0.22222222 0.33333333]
U_Y: [-1.         -0.78571429 -0.57142857 -0.35714286]
v:
 =[[57. 63. 82. 86.]
 [57. 63. 82. 86.]
 [59. 65. 84. 88.]
 [59. 65. 84. 88.]]...
v_i: [1228. 1228. 1256. 1256.]
v_j: [545. 599. 770. 806.]
delta = 1225.0952849085393
z = 153.1979027439562
delta >= z
Слід прийняти альтернативну гіпотезу H_1

r = 50
k = 55
U_X: [0.         0.02040816 0.04081633 0.06122449]
U_Y: [-1.         -0.94444444 -0.88888889 -0.83333333]
v:
 =[[106. 116. 126. 134.]
 [123. 133. 143. 151.]
 [114. 124. 134. 142.]
 [ 95. 105. 115. 123.]]...
v_i: [10508. 11426. 10940.  9914.]
v_j: [5196. 5686. 6176. 6568.]
delta = 11440.990271763387
z = 2766.7829362344587
delta >= z
Слід прийняти альтернативну гіпотезу H_1

r = 100
k = 105
U_X: [0.         0.01010101 0.02020202 0.03030303]
U_Y: [-1.         -0.97115385 -0.94230769 -0.91346154]
v:
 =[[500. 529. 542. 571.]
 [497. 526. 539. 568.]
 [506. 535. 548. 577.]
 [497. 526. 539. 568.]]...
v_i: [101376. 101064. 

<b>В. Критерій Спірмена.</b>
<p>Перевірити гіпотезу незалежності за допомогою критерія Спірмена при наступних значеннях параметра n</p>

<p>а) n=500 ; b) n=5000 ; с) n=50000</p>

In [5]:
def spearman(X,Y):
    n=len(X)
    X_sort = np.sort(X)
    Y_sort = np.sort(Y)
    R = np.array([np.where(X_sort == x)[0][0] + 1 for x in X])
    S = np.array([np.where(Y_sort == y)[0][0] + 1 for y in Y])
    p=1 - 6/(n*(n**2-1))*np.sum((R - S)**2)
    z = st.norm.ppf(1-0.05/2)
    criteria = z/np.sqrt(n)
    print(f'X_sort: {X_sort[0:4]}')
    print(f'Y_sort: {Y_sort[0:4]}')
    print(f'p = {p}')
    print(f'z = {z}')
    print(f'criteria = {criteria}')
    if np.abs(p)<criteria:
        print(f'|p| < criteria')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else:
        print(f'|p| >= criteria')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
def taskB():
    n=500
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    spearman(X,Y)
    
    n=5000
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    spearman(X,Y)
    
    n=50000
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    spearman(X,Y)
    
taskB()

X_sort: [0.00061787 0.00119528 0.00286163 0.00460778]
Y_sort: [-0.88750897 -0.88390658 -0.87477701 -0.86876573]
p = 0.3655230940923764
z = 1.959963984540054
criteria = 0.08765225405765815
|p| >= criteria
Слід прийняти альтернативну гіпотезу H_1

X_sort: [0.00045971 0.00070829 0.00147298 0.00154244]
Y_sort: [-0.9846332  -0.94764936 -0.94111519 -0.93700629]
p = 0.4262932408917296
z = 1.959963984540054
criteria = 0.027718076486993554
|p| >= criteria
Слід прийняти альтернативну гіпотезу H_1

X_sort: [1.92629290e-05 1.98350922e-05 2.18928506e-05 3.42901984e-05]
Y_sort: [-0.98399392 -0.9828157  -0.98071089 -0.97857767]
p = 0.4322510459897324
z = 1.959963984540054
criteria = 0.008765225405765815
|p| >= criteria
Слід прийняти альтернативну гіпотезу H_1



<b>С. Критерій Кендалла.</b>
<p>Перевірити гіпотезу незалежності за допомогою критерія Кендалла при наступних значеннях параметра n<p>
<p>а) n=500 ; b) n=5000 ; с) n=50000</p>

In [6]:
def kendall(X,Y):
    n=len(X)
    X_sort = np.sort(X)
    Y_sort = np.sort(Y)
    R = np.array([np.where(X_sort == x)[0][0] + 1 for x in X])
    S = np.array([np.where(Y_sort == y)[0][0] + 1 for y in Y])
    pairs=sorted(list(zip(R,S)),key=lambda x: x[0])
    V=np.array(list(zip(*pairs))[1])
    N=0
    for i in range(n):
        subV=V[i+1:]
        N+=len(subV[V[i-1]<subV])
        
    tau=(4*N)/(n*(n-1))-1
    z=st.norm.ppf(1-0.05/2)
    criteria=2*z/(3*np.sqrt(n))
    
    print(f'R: {R[0:4]}')
    print(f'S: {S[0:4]}')
    print(f'pairs = {pairs[0:4]}')
    print(f'V: {V[0:4]}')
    print(f'N = {N}')
    print(f'z = {z}')
    print(f'criteria = {criteria}')
    print(f'tau = {tau}')
    if np.abs(tau)<criteria:
        print(f'|tau| < criteria')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else:
        print(f'|tau| >= criteria')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')
    
    
def taskC():
    n=500
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    kendall(X,Y)
    
    n=5000
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    kendall(X,Y)
    
    n=50000
    ksi=np.random.uniform(low=0.0,high=1.0,size=n)
    eta=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=ksi
    Y=ksi+eta
    kendall(X,Y)
    
taskC()

R: [ 20 234 135  85]
S: [136 366  92 274]
pairs = [(1, 299), (2, 222), (3, 300), (4, 339)]
V: [299 222 300 339]
N = 80681
z = 1.959963984540054
criteria = 0.05843483603843876
tau = 0.2934829659318636
|tau| >= criteria
Слід прийняти альтернативну гіпотезу H_1

R: [4663  346 2369 2242]
S: [4831 2360 2902 4533]
pairs = [(1, 2004), (2, 363), (3, 2304), (4, 704)]
V: [2004  363 2304  704]
N = 8007345
z = 1.959963984540054
criteria = 0.018478717657995705
tau = 0.28143148629725956
|tau| >= criteria
Слід прийняти альтернативну гіпотезу H_1

R: [19582 26508 49417 48816]
S: [43169  4416 34865 25755]
pairs = [(1, 31990), (2, 72), (3, 33), (4, 1933)]
V: [31990    72    33  1933]
N = 808749143
z = 1.959963984540054
criteria = 0.005843483603843878
tau = 0.29402450929018586
|tau| >= criteria
Слід прийняти альтернативну гіпотезу H_1



<b>Завдання 3</b>. Перевірка гіпотези випадковості.
<p>Припустимо, що вибірка X=(x_1,...,x_n) утворюється за наступним правилом:</p>
<p>X_i=ksi_1+..._ksi_i, i=1,...,n, 
де {ksi_i} - це послідовність незалежних рівномірно
розподілених на [-1,1] випадкових величин.</p>
<p>Перевірити гіпотезу випадковості за допомогою критерію, що ґрунтується на
обчисленні кількості інверсій при наступних значеннях параметра n:</p>

<p>а) n=500 ; b) n=5000 ; с) n=50000</p>

In [7]:
def form_X(n):
    ksi=np.random.uniform(low=-1.0,high=1.0,size=n)
    X=np.zeros(n)
    temp=ksi[0]
    X[0]=temp
    for i in range(1,n):
        temp+=ksi[i]
        X[i]=temp
    return X

def calc_eta(X):
    n=len(X)
    eta=np.zeros(n)
    for i in range(n):
        subX=X[i+1:n]
        eta[i]=len(subX[X[i]>subX])
    return eta

def independence(X):
    n=len(X)
    eta=calc_eta(X)
    S=np.sum(eta)
    z=st.norm.ppf(1-0.05/2)
    criteria=abs((6/(n**(3/2)))*(S-((n*(n-1))/4)))
    print(f'n = {n}')
    print(f'Приблизні значення вибірки Х: {X[0:4]}')
    print(f'eta: {eta[0:4]}')
    print(f'S(X) = {S}')
    print(f'criteria =  (6/(n^(3/2)))*(S(X)-(n*(n-1)/4)) = {criteria}')
    print(f'z = {z}')
    if criteria<z:
        print(f'criteria < z')
        print(f'Статистичні дані не суперечать гіпотезі H_0\n')
    else: 
        print(f'criteria >= z')
        print(f'Слід прийняти альтернативну гіпотезу H_1\n')


def task():
    n=500
    X=form_X(n)
    independence(X)
    
    n=5000
    X=form_X(n)
    independence(X)
    
    n=50000
    X=form_X(n)
    independence(X)
    
task()

n = 500
Приблизні значення вибірки Х: [0.31507913 0.77078452 1.17132316 0.88435887]
eta: [0. 1. 3. 1.]
S(X) = 23345.0
criteria =  (6/(n^(3/2)))*(S(X)-(n*(n-1)/4)) = 20.94569595883603
z = 1.959963984540054
criteria >= z
Слід прийняти альтернативну гіпотезу H_1

n = 5000
Приблизні значення вибірки Х: [-0.47139161 -1.451249   -1.4480831  -0.4853556 ]
eta: [4998. 4985. 4985. 4995.]
S(X) = 9146650.0
criteria =  (6/(n^(3/2)))*(S(X)-(n*(n-1)/4)) = 49.17899378881191
z = 1.959963984540054
criteria >= z
Слід прийняти альтернативну гіпотезу H_1

n = 50000
Приблизні значення вибірки Х: [-0.56981679 -0.63216521 -1.10108138 -0.91223979]
eta: [34413. 34374. 34048. 34192.]
S(X) = 615615006.0
criteria =  (6/(n^(3/2)))*(S(X)-(n*(n-1)/4)) = 5.02980808865014
z = 1.959963984540054
criteria >= z
Слід прийняти альтернативну гіпотезу H_1

